### ISSUE TITLE
(Re-)evaluate use of repository pattern

### ISSUE THREAD

**Issue by Riari** [AndreasElia/laravel-forum#33]
I dunno if or how much this has been discussed already, but I'm not sure I see enough of a gain in using the repo pattern here. It does feel a little bit overengineered and adds complexity where it won't necessarily help.

I would suggest starting off by using Eloquent directly and, if Models start to get a little bloated, consider options to solve that without necessarily moving straight to the repository pattern.

**Comment by Dylan-DPC** [comment]
Well  it is built in a way to avoid major refactoring later. I feel its fine for now though it looks over-engineered atm. I would say leave as is

**Comment by Riari** [comment]
It's also built in a way that makes development and maintenance needlessly complicated. Better to keep it as lean as possible and only introduce patterns like this later on if they turn out to be truly justified.

That does potentially mean more work further down the line, but I think that's preferable compared to having the added complexity from day one.

**Comment by NowNewStart** [comment]
Also don't forget: This is a forum. We are limited on useful features anyways, I really don't believe that this project gets so big that it gets confusing

**Comment by Dylan-DPC** [comment]
I just thought of it as a safeguard and its better to build them out from the start rather "bring the house down". As people think this would scale that much, you are free to remove it

**Comment by Riari** [comment]
I'll do a PR

**Comment by NowNewStart** [comment]
Alright, I will change that in my PR too.

**Comment by AndreasElia** [comment]
Repository pattern removed in #39
