### ISSUE TITLE
Google Recaptcha as an option?

### ISSUE THREAD

**Issue by AndreasElia** [AndreasElia/laravel-forum#35]
Probably worth considerating at least as forums tend to get quite a lot of spam.

**Comment by Riari** [comment]
Personally, I would leave this entirely down to the discretion of the package user. Spam is only really an issue when guests can post, but if it's coming from registered users too, at that point it's about catching automated registrations and I would argue that's outside the problem domain for this package.

It would be easy enough for someone to implement custom measures like this if they want to. In theory, it's just a matter of overriding a view and controller action or form request.

**Comment by AndreasElia** [comment]
Good point, thanks @Riari!
