### ISSUE TITLE
Ugly namespacing 

### ISSUE THREAD

**Issue by Dylan-DPC** [AndreasElia/laravel-forum#51]
Pr #50 shed light on how ugly having a backslash in the namespace will be. Most users might end up skipping it all together and running into issues. We need a better way to handle this. Thoughts?

**Comment by AndreasElia** [comment]
We also need to chat about `forum.foo.bar` (example of course) as seen in PR #50 as currently `->name(config('forum.prefix').'.')` is very ugly.

Possibility of sticking this in a helper? 🤔

**Comment by AndreasElia** [comment]
Pretty sure we've handled this now by keeping `forum` as a permanent `as` and just allowing the `prefix` to be configured - if I'm wrong please let me know @Dylan-DPC.
