### ISSUE TITLE
Blade Component for DELETE Request

### ISSUE THREAD

**Issue by deleugpn** [AndreasElia/laravel-forum#62]
Usually `DELETE` request repeats some snippet of code like this one (extracted from #53 )

```
<form action="{{ $discussion->locked_at ? route('forum.lock.destroy') : route('forum.lock.store') }}" class="panel-options">
    {{ csrf_field() }}
    <input type="hidden" name="discussion_id" value="{{ $discussion->id }}">
    <input type="submit" value="{{ $discussion->locked_at ? 'Unlock' : 'Lock' }}" class="btn btn-{{ $discussion->locked_at ? 'danger' : 'success' }} pull-right">
</form>
```

You can see the `Form` declaration, the `csrf` field, some entity `id` and the `button`. In my projects I decided to replace that chunk of code into a component. This is my component that can be adjusted:

```
<form action="{{ route($route, $parameters) }}" method="POST">
    {{ method_field('DELETE') }}
    {{ csrf_field() }}
    <button type="submit" class="{{ $class or 'btn btn-danger' }}">
        @if(isset($label))
            {{ $label }}
        @else
            <i class="fa fa-remove"></i>
        @endif
    </button>
</form>
```

And then to use it

```
@include('components.delete', ['route' => 'tenant.lookup.segments.destroy', 'parameters' => [
                    'segment' => $segment->id],
                    'label' => __('Delete')
                ])
```

I know we can even improve the component with the new `@isset` directive that was introduced around Laravel 5.4.20.

**Comment by AndreasElia** [comment]
Will look into this when I get home this evening, thanks!

**Comment by AndreasElia** [comment]
@deleugpn after further thought I don't think a partial like this would be _that_ useful. Sometimes a form intended for deleting may contain hidden fields for parsing through correct data.

If you feel I'm in error please let me know and we can further discuss this and possibly re-open the issue.
