### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by connectkushal** [AndreasElia/laravel-forum#73]
On a fresh laravel install, doing this `composer require "andreaselia/laravel-forum"`  gives this:

```
[InvalidArgumentException]                                                                                                          
  Could not find package andreaselia/laravel-forum at any version for your minimum-stability (stable). Check the package spelling or  
   your minimum-stability 
```

**Comment by AndreasElia** [comment]
@connectkushal package isn't finished just yet and as a result the "read me" is incorrect. You'll have to manually install the package if you'd like to try it out so far (albeit a lot of polishing needs doing, and not everything currently works).

**Comment by Dylan-DPC** [comment]
yes the package hasn't been released to Packagist yet. so the above command won't work. If you want to try it add a repositories section to your `composer.json` file

**Comment by connectkushal** [comment]
I got it by adding it to the composer.json with the dev option
`"andreaselia/laravel-forum": "@dev"`

**Comment by connectkushal** [comment]
wanted to play around :) but i guess i'll have to wait. the dev version doesnt have the view files nor tests.

**Comment by AndreasElia** [comment]
@connectkushal I'll try and get a dev version up on packagist at some point this week/over the weekend.

**Comment by connectkushal** [comment]
@AndreasElia that would be great.
